# Generated by Django 3.0.8 on 2020-07-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(upload_to=''),
        ),
    ]
